import pyotp

username = "username"
secret = "secret key generated by create_user.py"

print("Secret:", secret)

uri = pyotp.totp.TOTP(secret).provisioning_uri(name=username, issuer_name="SecureAuthApp")
print("Scan this QR code URL in Google Authenticator:")
print("QR Code URL:", uri)


